import type { Brand, Decision, FunnelStage, Work } from '../../shared/contracts';
import { WORK_FILES } from '../core/paths';

export const MANAGED_MARKER = '<!-- latte:managed -->';

/** The funnel, in the order a person moves through it. Mirrors FunnelStage. */
const FUNNEL_STAGES: readonly FunnelStage[] = ['discovery', 'consideration', 'conversion', 'retention'];

/** How much of the working document is echoed into the instructions. */
const DOCUMENT_EXCERPT_CHARS = 6_000;

/** A role shipped by the pack: the personality a team member opens with. */
export interface PackRole {
  id: string;
  name: string;
  initial: string;
  summary: string;
  /** Appended to the runtime's system prompt for that member only. */
  instructions: string;
}

/** A writing skill Latte ships. Applies to every conversation unless turned off. */
export interface PackSkill {
  id: string;
  name: string;
  summary: string;
  body: string;
}

export interface InstructionPack {
  id: string;
  title: string;
  version: string;
  /** Workspace context rendered into CLAUDE.md / AGENTS.md. */
  body: string;
  /**
   * Marketing behaviour handed to EVERY conversation as a system prompt,
   * including the neutral assistant. Instruction files depend on the runtime
   * reading them; this travels through each runtime's own prompt channel.
   */
  base: string;
  roles: PackRole[];
  skills: PackSkill[];
}

/** One tracked deliverable, as the agent needs to see it. */
export interface InstructionDocument {
  kind: string;
  title: string;
  fileName: string;
  status: string;
  baseFileName?: string | null;
  /** Funnel stages this deliverable is filed under; empty means unclassified. */
  funnelStages?: FunnelStage[];
}

export interface InstructionsInput {
  brand: Brand;
  work: Work;
  decisions: Decision[];
  /** Tracked deliverables of this work, in creation order. */
  documents?: InstructionDocument[];
  /** Optional memory excerpt (already fetched, bounded by the caller). */
  memory?: string;
  /** Optional discipline pack (packs/marketing-core) rendered before the brand context. */
  pack?: InstructionPack | null;
  /** Engram project for this brand, stated explicitly (shared runtimes cannot rely on env). */
  memoryProject?: string | null;
  /** Skills the human left on. They travel here, once per session, not per request. */
  skills?: PackSkill[];
  /** Who is already open on this work: an agent that cannot see its team cannot ask for one. */
  team?: { roleId: string; roleName: string; status: string }[];
  /** Roles that exist and could still be called in. */
  available?: { id: string; name: string; summary: string }[];
}

function section(title: string, body: string, empty: string): string {
  const text = body.trim();
  return `## ${title}\n\n${text.length > 0 ? text : `_${empty}_`}\n`;
}

/**
 * The context a CLI agent sees when launched inside a work directory.
 * Claude Code reads CLAUDE.md, Codex and OpenCode read AGENTS.md; both get the
 * same rendered text. Global agent configuration is never touched.
 *
 * Order: discipline pack (how to work) -> brand -> document -> decisions -> rules.
 */
export function renderInstructions(input: InstructionsInput): string {
  const { brand, work, decisions, memory, pack, memoryProject } = input;
  const documentLines = (input.documents ?? [])
    .map((d) => {
      const status = d.status === 'draft' ? d.kind : `${d.kind}, ${d.status}`;
      const derived = d.baseFileName ? `, derived from ./${d.baseFileName}` : '';
      const stages = d.funnelStages?.length ? d.funnelStages.join(', ') : 'unclassified';
      return `- \`./${d.fileName}\` — ${d.title} (${status})${derived} — funnel: ${stages}`;
    })
    .join('\n');
  // What the funnel is MISSING is the finding; the per-file list alone buries it.
  const tracked = input.documents ?? [];
  const coverageLines = tracked.length === 0 ? '' : [
    'A deliverable can sit in several stages at once, or in none. A piece that mixes stages does none well.',
    '',
    ...FUNNEL_STAGES.map((stage) => `- \`${stage}\`: ${tracked.filter((d) => d.funnelStages?.includes(stage)).length}`),
    `- \`unclassified\`: ${tracked.filter((d) => !d.funnelStages?.length).length}`,
  ].join('\n');
  const team = input.team ?? [];
  const teamLines = team.map((m) => `- **${m.roleName}** (\`${m.roleId}\`) — ${m.status}`).join('\n');
  const availableLines = (input.available ?? [])
    .filter((r) => !team.some((m) => m.roleId === r.id))
    .map((r) => `- \`${r.id}\` — ${r.name}: ${r.summary}`)
    .join('\n');
  const decisionLines = decisions
    .map((d) => `- ${d.createdAt.slice(0, 10)} — ${d.text.trim().replace(/\s+/g, ' ')}`)
    .join('\n');
  const excerpt = work.brief.length > DOCUMENT_EXCERPT_CHARS
    ? `${work.brief.slice(0, DOCUMENT_EXCERPT_CHARS)}\n\n_[… truncated; read ./${WORK_FILES.brief} for the full text]_`
    : work.brief;

  const parts: string[] = [
    MANAGED_MARKER,
    '<!-- Generated by Latte from the discipline pack, the brand context, the working document and the decision log.',
    '     Edit those in the Latte app; this file is rewritten when a new agent session starts. -->',
    '',
    `# Latte · ${brand.name} · ${work.title}`,
    '',
    'You are working inside a Latte work directory. Latte is a local-first marketing',
    'workspace: the human directs, you execute, everything stays on this machine.',
    '',
  ];

  if (pack && pack.body.trim().length > 0) {
    parts.push(`<!-- latte:pack ${pack.id}@${pack.version} -->`, pack.body.trim(), '', '---', '');
  }

  parts.push(
    section('Brand context', brand.context, 'No brand context yet. Ask before assuming positioning, tone or audience.'),
    section('Tracked deliverables of this work', documentLines, `Only ./${WORK_FILES.brief} is tracked so far.`),
    section('Funnel coverage of this work', coverageLines, 'Nothing is tracked yet, so the funnel is empty.'),
    section(`The brief (current state of ./${WORK_FILES.brief})`, excerpt, 'The brief is still empty. Ask the human what the deliverable should be.'),
    section('Decisions already taken (do not reopen)', decisionLines, 'No decisions recorded yet.'),
    section('The team on this work', teamLines, 'You are the only one open on this work.'),
    section('Roles that could be called in', availableLines, 'Every shipped role is already open here.'),
  );

  if (memory && memory.trim().length > 0) {
    parts.push(section('Memory from previous sessions', memory, ''));
  }

  // Skills ride the instruction file, not the per-request prompt: the base
  // prompt is charged on every message and stays under its own budget.
  for (const skill of input.skills ?? []) {
    if (skill.body.trim().length === 0) continue;
    parts.push(`<!-- latte:skill ${skill.id} -->`, section(skill.name, skill.body.trim(), ''));
  }

  parts.push(
    '## Working rules',
    '',
    `- Each tracked file listed above is a deliverable of its own. Write in the one your task belongs to; \`./${WORK_FILES.brief}\` holds the ask, not every result.`,
    '- The human edits these same files from Latte. Re-read a file immediately before editing it and keep it valid Markdown.',
    '- A save made THROUGH Latte is refused when the file no longer matches the version Latte last saw, and the version on disk is kept for the human to resolve. A write you make directly to the file is not intercepted: it replaces what was there and Latte only notices afterwards. Re-read a file immediately before editing it.',
    '- You cannot register a document yourself: this file is managed by Latte. But a Markdown file you create at the top level of this folder is offered to the human in the app as "agregar como documento", and once they accept it gets versions and export. So: create the file, then say plainly that it is there and worth adding.',
    `- \`./${WORK_FILES.claude}\` and \`./${WORK_FILES.agents}\` are managed by Latte. Do not edit them.`,
    `- \`./${WORK_FILES.metaDir}/\` holds immutable snapshots. Never modify or delete anything in it.`,
    '- Stay inside this directory. Do not touch other brands, other works or global tool configuration.',
    '- When you take a decision that should stick, state it explicitly so the human can log it in Latte.',
    `- The funnel stages are \`${FUNNEL_STAGES.join('`, `')}\`. You do not assign them; the human does, when they adopt the file. What you can do is propose one: begin a Markdown file you create with a front matter block — a line \`---\`, then \`funnel: ${FUNNEL_STAGES[2]}, ${FUNNEL_STAGES[3]}\`, then a line \`---\`. Latte reads it when the human adopts the file and takes it out of the deliverable. Name only the stages the piece really serves.`,
    '- Say plainly which stages have nothing in them. An empty stage is a finding, not a detail.',
    '- You share this folder with the team, but not their conversations: you cannot read what they said and you cannot write to them. What you can do is ask for one of them, and the human decides.',
    '- To ask for a role, write a Markdown file at the top level whose front matter is a line `---`, then `para: <role id>`, then a line `---`, and put the request in the body: what you need from them, and what you already checked so they do not redo it. Latte offers it to the human, who opens that conversation with your request loaded. Ask only when the other role would genuinely do it better; doing the work yourself is usually the right answer.',
  );
  if (memoryProject) {
    parts.push(
      `- Memory: if you have Engram tools, always pass project \`${memoryProject}\` explicitly when saving or searching. Never rely on auto-detected project names; other brands must not see this brand's memories.`,
    );
  }
  parts.push('');

  return parts.join('\n');
}

export function isManagedFile(content: string | null): boolean {
  return content !== null && content.trimStart().startsWith(MANAGED_MARKER);
}
