import type { Brand, Decision, Work } from '../../shared/contracts';
import { WORK_FILES } from '../core/paths';

export const MANAGED_MARKER = '<!-- latte:managed -->';

/** How much of the working document is echoed into the instructions. */
const DOCUMENT_EXCERPT_CHARS = 6_000;

/** A role shipped by the pack: the personality a team member opens with. */
export interface PackRole {
  id: string;
  name: string;
  initial: string;
  summary: string;
  /** Appended to the runtime's system prompt for that member only. */
  instructions: string;
}

export interface InstructionPack {
  id: string;
  title: string;
  version: string;
  /** Workspace context rendered into CLAUDE.md / AGENTS.md. */
  body: string;
  /**
   * Marketing behaviour handed to EVERY conversation as a system prompt,
   * including the neutral assistant. Instruction files depend on the runtime
   * reading them; this travels through each runtime's own prompt channel.
   */
  base: string;
  roles: PackRole[];
}

/** One tracked deliverable, as the agent needs to see it. */
export interface InstructionDocument {
  kind: string;
  title: string;
  fileName: string;
  status: string;
  baseFileName?: string | null;
}

export interface InstructionsInput {
  brand: Brand;
  work: Work;
  decisions: Decision[];
  /** Tracked deliverables of this work, in creation order. */
  documents?: InstructionDocument[];
  /** Optional memory excerpt (already fetched, bounded by the caller). */
  memory?: string;
  /** Optional discipline pack (packs/marketing-core) rendered before the brand context. */
  pack?: InstructionPack | null;
  /** Engram project for this brand, stated explicitly (shared runtimes cannot rely on env). */
  memoryProject?: string | null;
}

function section(title: string, body: string, empty: string): string {
  const text = body.trim();
  return `## ${title}\n\n${text.length > 0 ? text : `_${empty}_`}\n`;
}

/**
 * The context a CLI agent sees when launched inside a work directory.
 * Claude Code reads CLAUDE.md, Codex and OpenCode read AGENTS.md; both get the
 * same rendered text. Global agent configuration is never touched.
 *
 * Order: discipline pack (how to work) -> brand -> document -> decisions -> rules.
 */
export function renderInstructions(input: InstructionsInput): string {
  const { brand, work, decisions, memory, pack, memoryProject } = input;
  const documentLines = (input.documents ?? [])
    .map((d) => {
      const status = d.status === 'draft' ? d.kind : `${d.kind}, ${d.status}`;
      const derived = d.baseFileName ? `, derived from ./${d.baseFileName}` : '';
      return `- \`./${d.fileName}\` — ${d.title} (${status})${derived}`;
    })
    .join('\n');
  const decisionLines = decisions
    .map((d) => `- ${d.createdAt.slice(0, 10)} — ${d.text.trim().replace(/\s+/g, ' ')}`)
    .join('\n');
  const excerpt = work.brief.length > DOCUMENT_EXCERPT_CHARS
    ? `${work.brief.slice(0, DOCUMENT_EXCERPT_CHARS)}\n\n_[… truncated; read ./${WORK_FILES.brief} for the full text]_`
    : work.brief;

  const parts: string[] = [
    MANAGED_MARKER,
    '<!-- Generated by Latte from the discipline pack, the brand context, the working document and the decision log.',
    '     Edit those in the Latte app; this file is rewritten when a new agent session starts. -->',
    '',
    `# Latte · ${brand.name} · ${work.title}`,
    '',
    'You are working inside a Latte work directory. Latte is a local-first marketing',
    'workspace: the human directs, you execute, everything stays on this machine.',
    '',
  ];

  if (pack && pack.body.trim().length > 0) {
    parts.push(`<!-- latte:pack ${pack.id}@${pack.version} -->`, pack.body.trim(), '', '---', '');
  }

  parts.push(
    section('Brand context', brand.context, 'No brand context yet. Ask before assuming positioning, tone or audience.'),
    section('Tracked deliverables of this work', documentLines, `Only ./${WORK_FILES.brief} is tracked so far.`),
    section(`The brief (current state of ./${WORK_FILES.brief})`, excerpt, 'The brief is still empty. Ask the human what the deliverable should be.'),
    section('Decisions already taken (do not reopen)', decisionLines, 'No decisions recorded yet.'),
  );

  if (memory && memory.trim().length > 0) {
    parts.push(section('Memory from previous sessions', memory, ''));
  }

  parts.push(
    '## Working rules',
    '',
    `- Each tracked file listed above is a deliverable of its own. Write in the one your task belongs to; \`./${WORK_FILES.brief}\` holds the ask, not every result.`,
    '- The human edits these same files from Latte. Re-read a file immediately before editing it and keep it valid Markdown.',
    '- A save made THROUGH Latte is refused when the file no longer matches the version Latte last saw, and the version on disk is kept for the human to resolve. A write you make directly to the file is not intercepted: it replaces what was there and Latte only notices afterwards. Re-read a file immediately before editing it.',
    '- A file you create that is not listed above is not tracked: no versions, no export. Tell the human to add it as a document if it matters.',
    `- \`./${WORK_FILES.claude}\` and \`./${WORK_FILES.agents}\` are managed by Latte. Do not edit them.`,
    `- \`./${WORK_FILES.metaDir}/\` holds immutable snapshots. Never modify or delete anything in it.`,
    '- Stay inside this directory. Do not touch other brands, other works or global tool configuration.',
    '- When you take a decision that should stick, state it explicitly so the human can log it in Latte.',
  );
  if (memoryProject) {
    parts.push(
      `- Memory: if you have Engram tools, always pass project \`${memoryProject}\` explicitly when saving or searching. Never rely on auto-detected project names; other brands must not see this brand's memories.`,
    );
  }
  parts.push('');

  return parts.join('\n');
}

export function isManagedFile(content: string | null): boolean {
  return content !== null && content.trimStart().startsWith(MANAGED_MARKER);
}
